### ISSUE TITLE
Is it just my setup

### ISSUE THREAD

**Issue by mrufflesmcghie** [juvpengele/laravel-vue-spa-blog#3]
Hi, I don't seem to be able to add posts etc from admin screen am I doing something wrong or is this still WIP
Thanks in advance

**Comment by ntqtuan** [comment]
Have you ever had an error like this?

run command: npm run dev

[webpack-cli] Error: spawn Unknown system error -86
    at ChildProcess.spawn (node:internal/child_process:415:11)
    at spawn (node:child_process:698:9)
    at Object.execFile (node:child_process:325:17)
    at Object.module.exports.fileCommandJson (/Users/panda/Sites/blog/node_modules/node-notifier/lib/utils.js:88:13)
    at NotificationCenter.notifyRaw (/Users/panda/Sites/blog/node_modules/node-notifier/notifiers/notificationcenter.js:81:11)
    at WebpackNotifierPlugin.compilationDone (/Users/panda/Sites/blog/node_modules/webpack-notifier/index.js:129:14)
    at _next1 (eval at create (/Users/panda/Sites/blog/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:39:1)
    at eval (eval at create (/Users/panda/Sites/blog/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:63:1) {
  errno: -86,
  code: 'Unknown system error -86',
  syscall: 'spawn'
}
